# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# development:
#   adapter: sqlite3
#   database: my_database_development
#   pool: 5
#   timeout: 5000

# test:
#   adapter: sqlite3
#   database: my_database_test
#   pool: 5
#   timeout: 5000

# production:
#   adapter: postgresql
#   database: my_database_production
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: capish_development
  pool: 5
  username: nimbo
  password: 123456
  host: localhost
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  database: capish_development
  pool: 5
  username: nimbo
  password: 123456
  host: localhost
  port: 5432